### ISSUE TITLE
Make it less work to finish games

### ISSUE THREAD

**Issue by mueller-ma** [meikpiep/gauguin#27]
I play with "pencil marks at start" and "auto-remove pencil marks". At some point in the late game it's quite easy to finish the game:

1. Find a cell with only one pencil mark
1. Enter that number as solution
1. Check cells in the same row and column if they just have been reduced to one pencil hint. If so, go to 1. in the list.

This is quite some work without any difficulty. Therefore it would be nice to have a button that does exactly this kind of alogrithm.

**Comment by meikpiep** [comment]
I got your point. I will think about if this type of button only makes sense when playing with initial pencil marks. Maybe it will be a new preference.

**Comment by stella-sf** [comment]
What bothers me most about this process is that you have to long-press each number to fill in the cell, rather than simply tapping. These controls are great while in the puzzle, but towards the end it just gets tedious and I would appreciate a button that switches the behavior so that long-pressing creates a note and tapping enters a number.

**Comment by meikpiep** [comment]
@stella-sf Thank you very much for sharing your thoughts.

It's amazing to see the rough edges of the game play and sharing ideas how to solve these. I hesitate to introduce a switch or mode, as this may tend to be none intuitive, but this is my first thought about it. Nevertheless, such a switch would work like a 'caps lock' to immediately fill numbers...

I'm currently implementing the idea of @mueller-ma to fill each remaining cell if it is possible to deduct each missing number via single possibles (=pencil marks). Actually, I'm not the type of player to actively use this feature, as I like the idea that I as the user solve the game by myself. But who knows... May be, we can struggle through a solution making the end game a step more comfortable.

I share your experience that its pretty mechanic of fill these cells... Any thoughts?

**Comment by stella-sf** [comment]
Personally I do like the mechanic process of "cleaning up" the board at the end, but I just want to be able to do so without spending a second on every box because I need to long press it. I definitely also see the appeal of a feature that would do it automatically, but I'd rather not use it personally :p

**Comment by meikpiep** [comment]
FYI: I'm into this, but not in the way mentioned before. I'l drop a comment here if the new feature gets into a release and would appreciate your feedback if this solves the pain (@stella-sf) and if the automatic solving (@mueller-ma) will still be relevant.

**Comment by meikpiep** [comment]
@mueller-ma @stella-sf version 0.15.0 arrived in F-Droid, would inviting you to test the feature if you want. :-)

**Comment by meikpiep** [comment]
#43

**Comment by bschwehn** [comment]
Thanks for adding fast-finishing mode!
I think I would enjoy the following improvements:

1. Only enter fast finishing mode when there is at least one cell with only one pencil mark. Currently it happens occasionally that you have only 3 cells that you can fill in with long press, then fast-finishing mode activates, but there is no other cell to use it with and you have to deactivate it again.
2. It can automatically deactivate once there are no more cells with only one pencil mark, since it cannot be used at this point and saves the user from closing manually.

   With these changes, I think it may also be possible to lower the activation trigger from 3 long presses to maybe 1 or 2, but not sure if that would really be better and/or if it would make it less usable when the "start with pencil filled in" feature is turned off.

**Comment by meikpiep** [comment]
@bschwehn and others:

I just released version 0.16.0 https://github.com/meikpiep/gauguin/releases/tag/v0.16.0, including both changes from you. Thanks for testing and your feedback!

Should be ready via Google play in a few hours and via F-Droid in 3-6 days.

**Comment by bschwehn** [comment]
Ah, this is great (It's not updated in play store nor F-Droid for me yet, I used the APK download to test), thank you very much, I like it!

**Comment by meikpiep** [comment]
Perfect, the release arrived at Google play just now (I suspect they speed down to make up with F-Droid :-P).

I will close this issue, feel free to reopen or open a new one if anything does not fit.

**Comment by meikpiep** [comment]
FYI: The F-Droid build has failed due to my fault, the next version 0.16.1 fixes is, but will be ready an 2-6 days, sorry for the delay.

**Comment by meikpiep** [comment]
FYI: Version 0.16.1 arrived in F-Driod, with optimized Fast Finishing Mode.
