### ISSUE TITLE
Useless "Undo" button in snackbar?

### ISSUE THREAD

**Issue by mueller-ma** [meikpiep/gauguin#30]
When I press the large blue question mark button a snackbar shows up with text "X mistakes, Y filled cells" and an undo button. It seems that this button doesn't do anything

**Comment by meikpiep** [comment]
This is supposed to be a shortcut if you encounter mistakes and want to go back and see if there are still mistakes, you may use 'undo' to do the undo and refresh the number of mistakes.

Never than less, while checking this, I found a bug that this undo was not quiet the same - this will be fixed in the next release.

Furthermore, you can only do a undo if the step to undo was being played in the current instance, that is if the app gets closed, the game is saved, but the undo info get lost. This will be fixed when I rewrite the load/save logic.

@mueller-ma Will you test another time when the next version with the slight fix is out?

**Comment by mueller-ma** [comment]
Ok, I see. Then maybe hide the button when there are 0 mistakes?

> Will you test another time when the next version with the slight fix is out?

Sure.

**Comment by meikpiep** [comment]
> Ok, I see. Then maybe hide the button when there are 0 mistakes?

Great idea, will be done, thanks!

**Comment by mh-tp** [comment]
be careful not to hide the button if a correct move was made after a mistake (just an idea, not understanding the code yet)

**Comment by meikpiep** [comment]
> be careful not to hide the button if a correct move was made after a mistake (just an idea, not understanding the code yet)

I will out look after such things.

The code dealing with mistakes, duplicates and warnings of cells is quiet old and does not even seem to be polished.

**Comment by meikpiep** [comment]
Just released version 0.13.0, fixing this: https://github.com/meikpiep/gauguin/releases/tag/v0.13.0

Should arrive on Google play in a few hours and via F-Droid after the next build, may be in 3-6 days.
