### ISSUE TITLE
feature request: additional number bases

### ISSUE THREAD

**Issue by ashkitten** [meikpiep/gauguin#35]
it would be cool to have additional bases like base 2, 8, 12, 16

**Comment by meikpiep** [comment]
Do you mean the set of numbers to be filled into the cells? If so, I don't get the idea, maybe you can describe an example? Like numbers from 8 on?

Or are we talking about displaying these numbers in a system other than the decimal system, e.g. F in hex instead of the decimal 15?

**Comment by ashkitten** [comment]
this would only affect the display, yes.

**Comment by meikpiep** [comment]
:bulb:

**Comment by meikpiep** [comment]
Implemented the feature and merged it into Main yesterday, will be included in next release.

**Comment by meikpiep** [comment]
FYI: I just released version 0.16.0 https://github.com/meikpiep/gauguin/releases/tag/v0.16.0, including this new feature, great idea, thank you a lot!

Should be ready via Google play in a few hours and via F-Droid in 3-6 days.

**Comment by meikpiep** [comment]
Finally arrived at F-Droid.

**Comment by Stefan-Ladwig** [comment]
I suggest reopening this because I would love to see base 12 aswell.
Some say *(me included)* the duodecimal system is superior to the decimal one. ([reddit post on this topic](https://www.reddit.com/r/changemyview/comments/1z7yci/the_duodecimal_or_dozenal_base_12_system_is/))

There are discussions on what symbols to use for 10 and 11, but A and B are probably the most obvious ones, though one might confuse it with the hexadecimal notation.
As described [here](https://en.wikipedia.org/wiki/Duodecimal) another symbol-pair is τ and ε, which are my favourites as they can be read as the first letter of ten and eleven.

**Comment by meikpiep** [comment]
I will add base 12, this was an interesting read, thank you.

**Comment by meikpiep** [comment]
Base 12 has been implemented and will be included into the next release. I used "A, B" as digits number 11 and 12 as this was straight forward and has more in common regarding hex numbers.

**Comment by Stefan-Ladwig** [comment]
> Base 12 has been implemented and will be included into the next release. I used "A, B" as digits number 11 and 12 as this was straight forward and has more in common regarding hex numbers.

Looking forward to the next release then 🙂
Your efforts are much appreciated 🎆

**Comment by meikpiep** [comment]
I just released a version including the duodecimal number system, see https://github.com/meikpiep/gauguin/releases/tag/v0.51.0

Feel free to report any issues or other ideas, I will close this issue for now.
